apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-deployment-feature
  namespace: kubernetes-cluster-rajivgogia
  labels:
    app: dotnet-app-feature
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-app-feature
  template:
    metadata:
      labels:
        app: dotnet-app-feature
    spec:
      containers:
        - name: dotnet-app-feature
          image: rajivgogia/productmanagementapi:i-rajivgogia-feature-latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-feature
  namespace: kubernetes-cluster-rajivgogia
spec:
  type: LoadBalancer
  selector: 
    app: dotnet-app-feature
  ports:    
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "app-settings"
  namespace: kubernetes-cluster-rajivgogia
  labels:
    app: "app-settings"
data:
  API_URL: "http://google.com"
  ENVIRONMENT: "dev"
  LANGUAGE: "English"
